spring:
  profiles:
    active: dev
  task:
    execution:
      pool:
        core-size: 10
        max-size: 10
  kafka:
    bootstrap-servers: ${KAFKA_1},${KAFKA_2},${KAFKA_3}
    producer:
      retries: 0
    consumer:
      group-id: ${KAFKA_GROUP_ID}



  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_IP}:${DB_NAME}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    #  naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: true
        #default_batch_fetch_size: 10
        type:
          descriptor:
            sql: trace


server:
  port: 20000